### ISSUE TITLE
error: could not find native static library `capstone`, perhaps an -L flag is missing?

### ISSUE THREAD

**Issue by japaric** [m4b/cargo-sym#1]
When compiling this crate *without* having capstone installed.

```
$ cargo install --git https://github.com/m4b/cargo-sym
    Updating git repository `https://github.com/m4b/cargo-sym`
    Updating git repository `https://github.com/m4b/goblin`
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/m4b/capstone-rs`
 Downloading rustc-demangle v0.1.3
 Downloading capstone-sys v0.1.0
   Compiling rustc-demangle v0.1.3
   Compiling quick-error v1.1.0
   Compiling ansi_term v0.9.0
   Compiling strsim v0.5.1
   Compiling unicode-segmentation v0.1.2
   Compiling gcc v0.3.38
   Compiling pkg-config v0.3.8
   Compiling rustc-serialize v0.3.21
   Compiling unicode-width v0.1.3
   Compiling byteorder v0.5.3
   Compiling libc v0.2.17
   Compiling goblin v0.0.6 (https://github.com/m4b/goblin#d0d5e00f)
   Compiling vec_map v0.6.0
   Compiling bitflags v0.7.0
   Compiling term_size v0.2.1
   Compiling clap v2.18.0
   Compiling capstone-sys v0.1.0
   Compiling toml v0.2.1
error: could not find native static library `capstone`, perhaps an -L flag is missing?

Build failed, waiting for other jobs to finish...
error: failed to compile `cargo-sym v0.0.3 (https://github.com/m4b/cargo-sym#dd6a04cd)`, intermediate artifacts can be found at `/tmp/cargo-install.9jZFb64amPLK`

Caused by:
  Could not compile `capstone-sys`.

To learn more, run the command again with --verbose.
```

### Meta

```
$ git rev-parse HEAD
dd6a04cd559332b7fd8999ec3244b2e2a53ac77c

$ rustc -V
rustc 1.14.0-nightly (cae6ab1c4 2016-11-05)

$ cargo -V
cargo 0.13.0-nightly (9c47815 2016-11-04)
```

**Comment by m4b** [comment]
Hmmm, I think maybe when capstone isn't installed, and it git clones and compiles from source _without_ using cmake, it isn't copied to the proper directories. Is this the output of `-vv`?

this is the capstone-sys build script:

``` rust
    if !cfg!(feature = "build_src") && pkg_config::find_library("capstone").is_ok() {
    } else {
        if !Path::new("capstone/.git").exists() {
            let _ = Command::new("git").args(&["submodule", "update", "--init", "--depth", "5"])
                .status();
        }
        if cfg!(feature = "build_src_cmake") {
            #[cfg(feature = "build_src_cmake")]
            cmake();
        } else {
            //let target = env::var("TARGET").unwrap();
            //let windows = target.contains("windows");
            // TODO: need to add this argument for windows 64-bit, msvc, dunno, read the COMPILE_MSVC.txt
            // file cygwin-mingw64
            let _ = Command::new("./make.sh").current_dir("capstone").status();
            println!("cargo:rustc-link-search=native=capstone");
        }
    }
    println!("cargo:rustc-link-lib=static=capstone");
```

i'm probably being stupid and forgot to copy things correctly in the non-cmake case :( sorry about this... will try to fix later

**Comment by m4b** [comment]
@japaric This should be fixed upstream now in the case when capstone not installed and not using cmake.

On that note, should the disassembler be:
1. optional?
2. do you think it should default to building from source or use system libs?
3. when building from source, use cmake by default (more cross platform but another dep)?

**Comment by japaric** [comment]
> should the disassembler be:

IMO

> optional?

I would start making it opt-in. If capstone doesn't work on some of the major OSes, I'd keep it opt-in. Otherwise, once I'm sure it works OK on the major OSes, I'll make it opt-out. I prefer to keep C dependencies optional unless my crate doesn't make sense without the C dependency (e.g. it's a rustic interface on top of some C library)

> do you think it should default to building from source or use system libs?

Unless there's some problem with the version of the system library (e.g. I depend on version 4.x but most people have installed version 3.x on their systems), I'd prefer to use the system library and fall back to build the source if it's not there.

> when building from source, use cmake by default (more cross platform but another dep)?

If it makes this crate work on more OSes (e.g. other than cmake there's no other way to make this compile on Windows) then I'd use cmake. Also, cmake is easy to install on Linux and macOS so this won't bother much users from those OSes.

**Comment by m4b** [comment]
I think this is somewhat fixed. However, this seems to not work correctly when installing using cmake with musl/non standard targets as a target and some other issues, need to investigate, though use cases for using capstone on aarch64 is not as popular most likely.
