### ISSUE TITLE
Does not work with lib crates on beta and nightly

### ISSUE THREAD

**Issue by malbarbo** [m4b/cargo-sym#6]
To reproduce:

```
> cargo new a && cd a
> cargo +stable build && cargo sym // works
> cargo +beta build && cargo sym // or +nightly, fails with the following error
target : "target/debug/liba.rlib"
```Error: Io(Error { repr: Custom(Custom { kind: Other, error: StringError("Cannot extract member a.o, not found") }) })
```

**Comment by m4b** [comment]
@malbarbo thanks for the report! Yea at some point rust changed the name of the object file inside static archives from simple `<crate-name>.o` to `<crate-name>-<hash>.o`, which I suspect is what's going on here.

I've been working on a big update to the goblin backend (should be able to add PE (Windows) symbol reader to cargo-sym now too, but I'm pretty busy and probably won't have time for a bit) which should hopefully resolve this.

**Comment by m4b** [comment]
Yea the issue is here: https://github.com/m4b/cargo-sym/blob/16c29b2fb4ff61fe7676c69e2ffc08b6cccc8361/src/main.rs#L409

It needs to turn into this basically:

```rust
        for member in archive.members() {
            if member.starts_with(&marksman.crate_name) && member.ends_with("0.o") {
                let bytes = archive.extract(member, bytes);
                // ideally would pattern match (or just recurse) on the identifier here but we're only supporting elf
                let elf = goblin::elf::Elf::parse(&bytes)?;
                return elf.analyze(&mut bytes, config)
            }
        }
```

But then I need to update the entire crate to use new goblin 0.0.7/master errors, other changes, etc.  Shouldn't be hard just a little tedious, you're welcome to help out :)

**Comment by malbarbo** [comment]
I gave it a [try](https://github.com/m4b/cargo-sym/pull/7), it's was not tedious after all.

**Comment by m4b** [comment]
PR should have closed, thanks again!
